### ISSUE TITLE
Push to Repo Feature

### ISSUE THREAD

**Issue by Habennin** [Semantic-Data-for-Humanities/OntoME#10]
OntoMe is an amazing tool for public, group, coordinated managed of ontology development. It also provides excellent built in tools for generating products of the ontology development process such as specification files, rdfs files and owl files. 

My feature idea / request, would be to add the ability to register repositories with an OntoMe project and have the idea of publishing to a repository. This could be a repo like github or a permanent deposit space like Zenodo. 

The idea here is that while OntoMe manages the development of the ontology and its products, those products need to be stored and distributed somewhere long term and probably well known. 

If there were a plugin to the repos then you could automatically push your ontology along with its metadata to specified repos. This could include links back to the OntoMe development site. As a result there would / could be a virtuous loop between the development software and the storage space.

**Comment by valamercery** [comment]
Thanks for your suggestion, this issue has been transferred to the Geovistory discussion section: https://github.com/orgs/geovistory/discussions/8
