### ISSUE TITLE
Insert Images in Ontology Description

### ISSUE THREAD

**Issue by Habennin** [Semantic-Data-for-Humanities/OntoME#11]
OntoMe provides the ability to do full metadata documentation for one's ontology including a text editor to write the intro material for the ontology.

The text editor however does not feature an image insert function. That said most CIDOC CRM extensions and CIDOC CRM itself have extension graphs, diagrams and other images to illustrate the use of the ontology in the introductory matter. 

This can be added to the doc afterwards, but it would be great to be able to include this in the main editing software, OntoMe

**Comment by valamercery** [comment]
Thanks for your suggestion, this issue has been transferred to the Geovistory discussion section: https://github.com/orgs/geovistory/discussions/9
