### ISSUE TITLE
RDF Generation of referenced super classes / properties generated in shortened form in RDFS

### ISSUE THREAD

**Issue by Habennin** [Semantic-Data-for-Humanities/OntoME#12]
**Describe the bug**

RDF Generation of referenced super classes / properties generated in shortened form in RDFS

**To Reproduce**

1. Go to https://ontome.net/namespace/72
2. Click on export refs and open the created file
3. Scroll down to any frbr class
4. See error (shorted URI instead of full name)

**Expected behavior**

Rather than shortening the URI from say "http://iflastandards.info/ns/fr/frbr/frbroo/F15_Complex_work" to "http://iflastandards.info/ns/fr/frbr/frbroo/F15", it should not do that, but print the full URI.

**Comment by valamercery** [comment]
Thanks for your bug report, this issue has been transferred to the Geovistory discussion section: https://github.com/orgs/geovistory/discussions/10
