### ISSUE TITLE
Do not generated referenced classes or properties in RDFS export

### ISSUE THREAD

**Issue by Habennin** [Semantic-Data-for-Humanities/OntoME#13]
**Describe the bug**

The RDFS export at present, will export both the classes of the namespace under development as well as any classes referenced from other namespaces with their full declaration.

The RDFS export does not need to and arguably should not produce the declarations for the referenced classes and properties because these already exist and are declared in the referenced ontology. 

It is sufficient for the RDFS export to print the referenced class or property URI in the about tag at the appropriate place e.g.: subclass of, domain, range. 

If the user needs the other class and property declarations they should load the relevant rdf of the standard they referenced.

To Reproduce

Go to https://ontome.net/namespace/72 
Click on export refs and open the created file
Scroll down and notice that it prints CRM and FRBR classes and properties but it doesn't need to.
Expected behavior

Rather than printing these class and property declarations, it should not.

**Comment by valamercery** [comment]
Thanks for your bug report, this issue has been transferred to the Geovistory discussion section: https://github.com/orgs/geovistory/discussions/11
