### ISSUE TITLE
New namespace

### ISSUE THREAD

**Issue by mquantin** [Semantic-Data-for-Humanities/OntoME#14]
Is there a way to add new namespaces to a projet or to the whole ontome? 
For example I have a projet using CIDOC, [RDAA](http://www.rdaregistry.info/Elements/a/), [W3C time ontology](https://www.w3.org/TR/owl-time/) and other standards ontologies; 
These are not among the available namespaces in ontome. 
How to add them? 

pulling from a trusted source like https://triplydb.com may be a solution? 
another solution would be to add a rdf file (online file).

**Comment by valamercery** [comment]
Thanks for your feedback, this issue has been transferred to the Geovistory discussion section: https://github.com/orgs/geovistory/discussions/12
