### ISSUE TITLE
Downloadable machine-readable version of the ontologies

### ISSUE THREAD

**Issue by pasqLisena** [Semantic-Data-for-Humanities/OntoME#2]
**Is your feature request related to a problem? Please describe.**
In order to easily reuse or extend the ontologies collected in OntoME, it would be nice to have the possibility to access/download a machine-readable version, in owl, rdf or whatever.

**Describe the solution you'd like**
Link to the repository or owl file.

**Describe alternatives you've considered**
N.a.

**Additional context**
N.a.

**OntoME username (optional):**
pasqlisena

**Comment by valamercery** [comment]
Thanks for your feedback, this problem appeared recently, we are working to fix this issue.

**Comment by valamercery** [comment]
This bug has been fixed, you should now be able to upload an owl/rdf version of a namespace.
