### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by gaetanmuck** [Semantic-Data-for-Humanities/OntoME#3]
**Describe the bug**
Hello, I got a 500 error when calling an http request on a certain path

**To Reproduce**
1. Call https://ontome.net/property/test-whatever 
2. see error

**Desktop (please complete the following information):**
 - Browser: Chromium

Have a nice day!

**Comment by valamercery** [comment]
Thanks for your feedback, a 404 error would indeed be more relevant here. We'll fix that.

**Comment by valamercery** [comment]
Fixed!
