### ISSUE TITLE
Duplicated full scren button on the page of the namespace graph

### ISSUE THREAD

**Issue by sunrevp** [Semantic-Data-for-Humanities/OntoME#4]
**Describe the bug**
On the following page : https://ontome.net/namespace/36/edit#graph
there are two buttons "WebVOWL". 

**To Reproduce**
1. Go to https://ontome.net/namespace/36/edit#graph.
2. Look at the buttons. 

This seems to be a copy/paste problem in the code of the template of the page.

**Expected behavior**
Only one button is needed. 

**Desktop (please complete the following information):**
 - OS: linux Mint 20.1 Ulyssa
 - Browser firefox 89.0.2

**Comment by valamercery** [comment]
Thanks for your feedback. This duplication is not due to a copy/paste in the code but to a problem with WebVOWL which does not allow to display the graph in OntoME (which should be between the two buttons). This is a known problem and the fix is in the pipeline.
