### ISSUE TITLE
Error 500 when saving property identification

### ISSUE THREAD

**Issue by natuk** [Semantic-Data-for-Humanities/OntoME#5]
**Issue**
Changing the identification label of a property throws a server error 500.

**To Reproduce**
1. Go to `https://ontome.net/property/1243/edit#identification`
2. Click on the pencil icon next to identifier label → an editable filed appears
3. Change the label in the field to `apP27`
4. Click `Save`

**Expected behavior**
The identification label of the property to change.

**Additional context**
The problem does not seem to occur when changing class identification labels.

**OntoME username:**
avelios

**Comment by valamercery** [comment]
Hi, thanks for your report. This bug has been fixed, you should now be able to edit the property identifier.

**Comment by natuk** [comment]
Looks good, thank you.
