### ISSUE TITLE
Deletion of entities

### ISSUE THREAD

**Issue by tla** [Semantic-Data-for-Humanities/OntoME#7]
**Is your feature request related to a problem? Please describe.**
Now that ongoing namespaces are hidden by default, would it be possible to implement deletion of classes and properties? In any event, I don't see any way to do this in the current interface and there is no hint in the user guide that it is possible.

**OntoME username (optional):**
tla

**Comment by valamercery** [comment]
Thanks for your suggestion, this issue has been transferred to the Geovistory discussion section : https://github.com/orgs/geovistory/discussions/5
