### ISSUE TITLE
Generate Inverse Properties in RDF

### ISSUE THREAD

**Issue by Habennin** [Semantic-Data-for-Humanities/OntoME#8]
OntoMe currently auto generates RDF of the managed ontology using its export function.

This RDF feature is already very useful. However, it only generates the forward direction of properties and not their inverse. 

In CIDOC CRM especially, the explicit generation of the inverse property is standard. Its URI is generated by the namespace + its identifier + "i" + its label.

Currently these have to be generated manually after the fact and this is time consuming and error prone.

Ideally the system could generate these as part of the regular RDF export functionality.

**Comment by Habennin** [comment]
To add an example of how this would look based on OntoMe, I am attaching here my hand crafted version for CRMaaa. It takes about two days to hand write and audit 80 inverse properties that have super properties and it is an error prone process which requires multiple revisions. That said, it does give you a chance to really double check your work!

[CRMaaa_v1.5_inverses.txt](https://github.com/Semantic-Data-for-Humanities/OntoME/files/13304028/CRMaaa_v1.5_inverses.txt)

**Comment by valamercery** [comment]
Thanks for your suggestion, this issue has been transferred to the Geovistory discussion section : https://github.com/orgs/geovistory/discussions/6
