### ISSUE TITLE
More Readable Organization of the Export RDF Output

### ISSUE THREAD

**Issue by Habennin** [Semantic-Data-for-Humanities/OntoME#9]
Currently the RDF output feature is very helpful. It could possibly be made even more helpful by making the output more readable.

Currently it outputs the rdf with very little formatting.

It could be helpful for it to put blank lines betweeen class declarations and property declarations.

It could be nice if it put in a section name for the classes and then the properties using comments.

Like  

`<!-- These are the x classes of ontology y version q -->`

Like 

`
`

It could be nice if it were to put in the version information as well as other metadata for the production data of the RDFS, a little like how the docx output already works. CIDOC CRM puts in a label like this:

<owl:versionInfo>RDFs Implementation (September 2022) of CIDOC-CRM 7.1.2</owl:versionInfo>

The present output currently generates declarations for referenced classes and properties of other ontologies. I don't think it is necessary for it to do this. If one needs those declarations one should just load the other ontology. Otherwise the reference is enough.

The order that it prints out the properties in the RDFS is hard to read.

For classes currently it is:

```xml
<rdfs:Class rdf:about="xxxx">
    <skos:notation rdf:datatype="http://www.w3.org/2001/XMLSchema#string">number</skos:notation>
    <rdfs:comment xml:lang="en" rdf:datatype="http://www.w3.org/2001/XMLSchema#string">description</rdfs:comment>
    <rdfs:label xml:lang="en">label</rdfs:label>
    <rdfs:subClassOf>
      <rdfs:Class rdf:about="yyy"/>
    </rdfs:subClassOf>
  </rdfs:Class>
```

I suggest

```xml
<rdfs:Class rdf:about="xxxx">
     <rdfs:label xml:lang="en">label</rdfs:label>
     <skos:notation rdf:datatype="http://www.w3.org/2001/XMLSchema#string">number</skos:notation>
     <rdfs:comment xml:lang="en" rdf:datatype="http://www.w3.org/2001/XMLSchema#string">description</rdfs:comment>
    <rdfs:subClassOf>
      <rdfs:Class rdf:about="yyy"/>
    </rdfs:subClassOf>
  </rdfs:Class>
```

My argument for the change is that you want to read the label and annotation information together before descriptions etc.

Currently properties print as:

```xml
<rdf:Property rdf:about="xxx">
    <rdfs:range rdf:resource="yyy"/>
    <rdfs:comment xml:lang="en">description
    </rdfs:comment>
    <rdfs:label xml:lang="en">label</rdfs:label>
    <skos:notation rdf:datatype="http://www.w3.org/2001/XMLSchema#string">number</skos:notation>
    <rdfs:domain rdf:resource="qqqq"/>
    <rdfs:subPropertyOf>
      <rdf:Property rdf:about="zzzz"/>
    </rdfs:subPropertyOf>
  </rdf:Property>
```

I propose

```xml
<rdf:Property rdf:about="xxx">
     <rdfs:label xml:lang="en">label</rdfs:label>
     <skos:notation rdf:datatype="http://www.w3.org/2001/XMLSchema#string">number</skos:notation>
    <rdfs:comment xml:lang="en">description
    </rdfs:comment>
    <rdfs:domain rdf:resource="qqqq"/>
    <rdfs:range rdf:resource="yyy"/>
    <rdfs:subPropertyOf>
      <rdf:Property rdf:about="zzzz"/>
    </rdfs:subPropertyOf>
  </rdf:Property>
```

My argument for the change is the same as for classes. I also think that domain should print before range and they should go together because this is how you understand what the property does.

**Comment by valamercery** [comment]
Thanks for your suggestion, this issue has been transferred to the Geovistory discussion section: https://github.com/orgs/geovistory/discussions/7
